In [2]:
def test():
    print('test()for function')
    return
test()

test()for function


In [4]:
class Demo:
    def test(self):
        print("test()for the class and  method")
        return
    
obj=Demo()
obj.test
    

<bound method Demo.test of <__main__.Demo object at 0x03CC9D70>>

In [6]:
class Demo1:
    def fact(self,n):
        #return the factorial
        return
    
p1=Demo1()
p1.fact(5)

In [9]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact

p1=Demo1()
print(p1.fact(5))

120


In [15]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
        
        
c1=Demo2(10,20)
print(c1.add(100,200))


300


In [16]:
class person():
    #constrution
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isEmployee(self):
        return False
    
#Derived class
class Employee(person):
    def isEmployee(self):
        return True
    
emp=person("anil")
print(emp.getname(),emp.isEmployee())

emp1=Employee("akhil")
print(emp1.getname(),emp1.isEmployee())


anil False
akhil True


#  Python numpy

In [17]:
import numpy as np
lst=[1,2,3,4,5]
array=np.array(lst)
print(array)

[1 2 3 4 5]


In [18]:
lst=[1,2,3,4,5]
array=np.array(lst)
array+10

array([11, 12, 13, 14, 15])

In [20]:
lst=[1,2,3,4,5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(5,)
int32


In [21]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(4,5,6),(3,2,1)])
print(a2.shape)


(2, 3)
(2, 3)


In [22]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
#np.ones(shape,dtype=float,order='c')
np.ones((4,3),dtype=np.int64)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [28]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [29]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2]=5
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [30]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[1][3]=5
np.asarray(a)[3][3]=23
print(a)



[[ 1  1  1  1]
 [ 1  1  1  5]
 [ 1  1  1  1]
 [ 1  1  1 23]]


In [26]:
# Indexing and slicing of numpy 
a1=np.array([(1,2,3),(4,5,6)])
print(a1)


[[1 2 3]
 [4 5 6]]


In [25]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [31]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))


[4.84897078 3.6873066  4.53869244 4.82373477 3.47218805 2.30226741
 5.21742787 4.53870457 6.10904507 4.61063906]
min value= 2.302267410288485
max value= 6.109045071454405
mean value= 4.414897661904975
median value= 4.57467181473541


In [32]:
c1 = np.array([1,2])
c2 = np.array([4,5])
np.dot(c1,c2)
              

14

In [39]:
c1 = np.array([(1,2),(3,4)])
c2 = np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

## Panda Basics

In [1]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
    "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
    "Mobile Number":[99,44,55,22,33,41]}

b=pd.DataFrame(dict)
print(b)

b.index=["01","02","03","04","05","06"]
print(b)

     Name           EmailID  Mobile Number
0    Anil    anil@gmail.com             99
1   Akhil   akhil@gmail.com             44
2  Dinesh  dinesh@gmail.com             55
3  Harsha  harsha@gmail.com             22
4    Ajay    ajay@gmail.com             33
5  Kranth  kranth@gmail.com             41
      Name           EmailID  Mobile Number
01    Anil    anil@gmail.com             99
02   Akhil   akhil@gmail.com             44
03  Dinesh  dinesh@gmail.com             55
04  Harsha  harsha@gmail.com             22
05    Ajay    ajay@gmail.com             33
06  Kranth  kranth@gmail.com             41
